FROM ubuntu:latest

RUN apt-get --yes update && \
  apt-get --yes install openjdk-8-jre unzip curl

RUN cd /tmp && \
  curl -O https://www.yourkit.com/download/YourKit-JavaProfiler-2017.02-b75.zip && \
  unzip YourKit-JavaProfiler-2017.02-b75.zip

ADD run.sh /data/app/
ADD keys.jceks /data/app/
ADD jetty-thread-test/target/server.jar /data/app/

EXPOSE 10001
EXPOSE 1338

ENTRYPOINT ["/data/app/run.sh"]
